using Financeiro.Application.Common; using Financeiro.Application.DTOs; using Financeiro.Application.Interfaces; using Financeiro.Domain.Entities; using Financeiro.Domain.Interfaces; using Financeiro.Domain.Interfaces.Repositories;
namespace Financeiro.Application.Services;
public class PeriodoService : IPeriodoService {
  private readonly IPeriodoPagamentoRepository _periodos; private readonly IDespesaPeriodoRepository _despesas; private readonly IUnitOfWork _uow;
  public PeriodoService(IPeriodoPagamentoRepository periodos, IDespesaPeriodoRepository despesas, IUnitOfWork uow){_periodos=periodos;_despesas=despesas;_uow=uow;}
  public async Task<Result<PeriodoResponseDto>> AddDespesaAsync(Guid periodoId, DespesaRequestDto request, CancellationToken cancellationToken=default){ var p=await _periodos.GetByIdAsync(periodoId,cancellationToken); if(p is null) return Result<PeriodoResponseDto>.Fail("Período não encontrado."); var d=new DespesaPeriodo(periodoId,request.Descricao,request.Valor,request.Tipo); await _despesas.AddAsync(d,cancellationToken); await _uow.SaveChangesAsync(cancellationToken); p=await _periodos.GetByIdAsync(periodoId,cancellationToken); return Result<PeriodoResponseDto>.Ok(Map(p!),"Despesa adicionada com sucesso."); }
  public async Task<Result<PeriodoResponseDto>> CreateAsync(PeriodoRequestDto request,CancellationToken cancellationToken=default){ var p=new PeriodoPagamento(request.MesReferencia,request.DiaPagamento,request.Pessoa,request.Salario); await _periodos.AddAsync(p,cancellationToken); await _uow.SaveChangesAsync(cancellationToken); return Result<PeriodoResponseDto>.Ok(Map(p),"Período criado com sucesso."); }
  public async Task<Result<bool>> DeleteAsync(Guid id,CancellationToken cancellationToken=default){ var p=await _periodos.GetByIdAsync(id,cancellationToken); if(p is null) return Result<bool>.Fail("Período não encontrado."); _periodos.Remove(p); await _uow.SaveChangesAsync(cancellationToken); return Result<bool>.Ok(true,"Período removido com sucesso."); }
  public async Task<Result<bool>> DeleteDespesaAsync(Guid periodoId, Guid despesaId, CancellationToken cancellationToken=default){ var d=await _despesas.GetByIdAsync(despesaId,cancellationToken); if(d is null || d.PeriodoPagamentoId!=periodoId) return Result<bool>.Fail("Despesa não encontrada."); _despesas.Remove(d); await _uow.SaveChangesAsync(cancellationToken); return Result<bool>.Ok(true,"Despesa removida com sucesso."); }
  public async Task<Result<IReadOnlyList<PeriodoResponseDto>>> GetAllAsync(CancellationToken cancellationToken=default){ var items=await _periodos.GetAllAsync(cancellationToken); return Result<IReadOnlyList<PeriodoResponseDto>>.Ok(items.Select(Map).OrderBy(x=>x.DiaPagamento).ToList().AsReadOnly()); }
  public async Task<Result<PeriodoResponseDto>> UpdateAsync(Guid id, PeriodoRequestDto request, CancellationToken cancellationToken=default){ var p=await _periodos.GetByIdAsync(id,cancellationToken); if(p is null) return Result<PeriodoResponseDto>.Fail("Período não encontrado."); p.Atualizar(request.MesReferencia,request.DiaPagamento,request.Pessoa,request.Salario); _periodos.Update(p); await _uow.SaveChangesAsync(cancellationToken); return Result<PeriodoResponseDto>.Ok(Map(p),"Período atualizado com sucesso."); }
  private static PeriodoResponseDto Map(PeriodoPagamento p){ var despesas=(p.Despesas ?? Array.Empty<DespesaPeriodo>()).Select(d=>new DespesaResponseDto{Id=d.Id,Descricao=d.Descricao,Valor=d.Valor,Tipo=d.Tipo}).ToList(); var total=despesas.Sum(x=>x.Valor); return new PeriodoResponseDto{Id=p.Id,MesReferencia=p.MesReferencia,DiaPagamento=p.DiaPagamento,Pessoa=p.Pessoa,Salario=p.Salario,Despesas=despesas,TotalDespesas=total,Saldo=p.Salario-total}; }
}
